version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dashboard_db
      POSTGRES_USER: dashboard_user
      POSTGRES_PASSWORD: dashboard_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  news-service:
    build: ./services/news
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgres://dashboard_user:dashboard_pass@postgres:5432/dashboard_db?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - postgres
      - redis

  jobs-service:
    build: ./services/jobs
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgres://dashboard_user:dashboard_pass@postgres:5432/dashboard_db?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - LINKEDIN_API_KEY=${LINKEDIN_API_KEY}
    depends_on:
      - postgres
      - redis

  videos-service:
    build: ./services/videos
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgres://dashboard_user:dashboard_pass@postgres:5432/dashboard_db?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    depends_on:
      - postgres
      - redis

  deals-service:
    build: ./services/deals
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgres://dashboard_user:dashboard_pass@postgres:5432/dashboard_db?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - AMAZON_API_KEY=${AMAZON_API_KEY}
      - FLIPKART_API_KEY=${FLIPKART_API_KEY}
    depends_on:
      - postgres
      - redis

  recommendation-service:
    build: ./services/recommendation
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgres://dashboard_user:dashboard_pass@postgres:5432/dashboard_db?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - WOLFRAM_API_KEY=${WOLFRAM_API_KEY}
    depends_on:
      - postgres
      - redis

  user-service:
    build: ./services/user
    ports:
      - "8006:8000"
    environment:
      - DATABASE_URL=postgres://dashboard_user:dashboard_pass@postgres:5432/dashboard_db?sslmode=disable
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  nft-service:
    build: ./services/nft
    ports:
      - "8007:8000"
    environment:
      - DATABASE_URL=postgres://dashboard_user:dashboard_pass@postgres:5432/dashboard_db?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - VERBWIRE_API_KEY=${VERBWIRE_API_KEY}
    depends_on:
      - postgres
      - redis

  api-gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - NEWS_SERVICE_URL=http://news-service:8000
      - JOBS_SERVICE_URL=http://jobs-service:8000
      - VIDEOS_SERVICE_URL=http://videos-service:8000
      - DEALS_SERVICE_URL=http://deals-service:8000
      - RECOMMENDATION_SERVICE_URL=http://recommendation-service:8000
      - USER_SERVICE_URL=http://user-service:8000
      - NFT_SERVICE_URL=http://nft-service:8000
    depends_on:
      - news-service
      - jobs-service
      - videos-service
      - deals-service
      - recommendation-service
      - user-service
      - nft-service

volumes:
  postgres_data:
